// Autogenerated Song repository file
package repository

import "github.com/guilherme-or/go-cleanarch-starter/internal/domain/entity"

type SongRepository interface {
	FindByDuration(durationInS int) ([]*entity.Song, error)
	FindByArtist(artistID int) ([]*entity.Song, error)
	FindByAlbum(albumID int) ([]*entity.Song, error)
}
