services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default

volumes:
  default:

networks:
  default: